const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const { createStrategy, createMarketStrategy } = await import('../src/options.ts');
  const state = createStrategy('long-put');
  const record = { id: 'lifecycle-browser-fixture', title: 'Recorded close test', revision: 1, createdAt: state.valuationTimestamp, updatedAt: state.valuationTimestamp, state, snapshot: null, lifecycle: null };
  const projection = { status: 'options-active', active: state, stock: null, asOf: state.valuationTimestamp, requiresRevaluation: false, grossRealizedPnl: 0, allowance: 5, netClosedPnl: null };
  const closed = { ...projection, status: 'closed', active: null, grossRealizedPnl: 70, netClosedPnl: 65 };
  const snapshot = { id: 'lifecycle-dated-quotes', underlying: 'SPY', source: 'Tastytrade', retrievedAt: '2026-09-05T18:00:00.000Z', spot: 100, spotAsOf: '2026-09-05T17:59:58.000Z', availableExpiries: ['2026-09-18'], contracts: [{ contractId: 'SPY   260918P00100000', type: 'put', strike: 100, expiry: '2026-09-18T20:00:00.000Z', multiplier: 100, bid: 2, ask: 2.1, iv: .2, quoteAsOf: '2026-09-05T17:59:57.000Z' }] };
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
  try {
    const page = await browser.newPage();
    const errors = [], commits = [];
    let valuations = 0;
    let malformedRemaining = false;
    let marketPhase = false;
    const saveMutations = [];
    let closedRecord = null;
    const corrections = [];
    const voids = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.route('**/api/feed/**', route => route.fulfill({ status: 503, json: { error: { message: 'Mock browser: feed disabled' } } }));
    await page.route('**/api/strategies**', async route => {
      const request = route.request(), path = new URL(request.url()).pathname;
      if (['PUT', 'DELETE'].includes(request.method()) || request.method() === 'POST' && path === '/api/strategies') saveMutations.push({ method: request.method(), path });
      if (path === '/api/strategies') return route.fulfill({ json: { strategies: [record] } });
      if (path.endsWith('/lifecycle')) {
        if (closedRecord && !marketPhase) return route.fulfill({ json: { record: closedRecord, projection: closed } });
        const active = createMarketStrategy('long-put', snapshot);
        active.legs[0].contracts = 2;
        active.legs[0].entryPrice = 2.3;
        active.pricing.entryMode = 'fixed';
        return route.fulfill({ json: { record, projection: marketPhase ? { ...projection, active } : projection } });
      }
      if (request.method() === 'GET') { marketPhase = true; return route.fulfill({ json: { record: { ...record, state: createMarketStrategy('long-put', snapshot), snapshot } } }); }
      const body = request.postDataJSON();
      if (path.includes('/close-voids')) {
        assert.equal(body.revision, 3);
        assert.deepEqual(Object.keys(body).sort(), ['revision', 'void']);
        assert.deepEqual(Object.keys(body.void).sort(), ['closeId', 'id', 'reason', 'recordedAt']);
        assert.equal(body.void.closeId, commits[0].close.id);
        assert.equal(body.void.reason, 'Close recorded in error');
        const restored = { ...projection, requiresRevaluation: true };
        if (path.endsWith('/preview')) return route.fulfill({ json: { revision: 3, projection: restored } });
        voids.push(body);
        if (voids.length === 1) return route.abort();
        if (voids.length === 2) return route.fulfill({ status: 429, json: { error: { message: 'Void rate limited' } } });
        closedRecord = { ...closedRecord, revision: 4, lifecycle: { ...closedRecord.lifecycle, closeVoids: [body.void] } };
        return route.fulfill({ json: { record: closedRecord, projection: restored } });
      }
      if (path.includes('/price-corrections')) {
        assert.equal(body.revision, 2);
        assert.deepEqual(Object.keys(body).sort(), ['correction', 'revision']);
        assert.deepEqual(Object.keys(body.correction).sort(), ['closeId', 'id', 'price', 'reason', 'recordedAt']);
        assert.equal(body.correction.closeId, commits[0].close.id);
        assert.equal(body.correction.price, 3.98765);
        assert.equal(body.correction.reason, 'Transcription correction');
        assert.equal(new Date(body.correction.recordedAt).toISOString(), body.correction.recordedAt);
        const corrected = { ...closed, grossRealizedPnl: 168.765, netClosedPnl: 163.765 };
        if (path.endsWith('/preview')) return route.fulfill({ json: { revision: 2, projection: corrected } });
        corrections.push(body);
        if (corrections.length === 1) return route.abort();
        if (corrections.length === 2) return route.fulfill({ status: 429, json: { error: { message: 'Correction rate limited' } } });
        closedRecord = { ...closedRecord, revision: 3, lifecycle: { ...closedRecord.lifecycle, priceCorrections: [body.correction] } };
        return route.fulfill({ json: { record: closedRecord, projection: corrected } });
      }
      assert.equal(body.revision, 1);
      if (path.endsWith('/valuation')) {
        valuations++;
        assert.deepEqual(Object.keys(body).sort(), ['basis', 'revision', 'snapshotId']);
        assert.equal(body.snapshotId, snapshot.id);
        const remainingState = createMarketStrategy('long-put', snapshot, body.basis);
        remainingState.name = 'Remaining holdings';
        remainingState.feeAllowance = 0;
        remainingState.legs[0].contracts = 2;
        remainingState.legs[0].entryPrice = 2.3;
        remainingState.pricing.entryMode = 'fixed';
        if (malformedRemaining) remainingState.pricing.snapshotId = 'wrong-snapshot';
        return route.fulfill({ json: { revision: 1, valuation: { snapshotId: snapshot.id, basis: body.basis, retrievedAt: snapshot.retrievedAt, oldestQuoteAt: snapshot.contracts[0].quoteAsOf, newestQuoteAt: snapshot.spotAsOf, historical: true, grossRealizedPnl: 70, unrealizedPnl: 20, allowance: 5, combinedPnl: 85, remainingState, disclosure: 'Dated estimate, not a fill or live return.' } } });
      }
      assert.equal(body.close.assetId, `option:${state.legs[0].id}`);
      assert.match(body.close.id, /^[0-9a-f-]{36}$/);
      assert.equal(body.close.at, '2026-09-04T20:00:00.000Z');
      if (path.endsWith('/preview')) return route.fulfill({ json: { revision: 1, projection: closed } });
      commits.push(body);
      if (commits.length === 1) return route.abort();
      if (commits.length === 2) return route.fulfill({ status: 429, json: { error: { message: 'Rate limited' } } });
      closedRecord = { ...record, revision: 2, lifecycle: { schemaVersion: 1, initial: state, closes: [{ ...body.close, side: 'long', entryPrice: 2.3, multiplier: 100, contractId: state.legs[0].contractId }] } };
      return route.fulfill({ json: { record: closedRecord, projection: closed } });
    });
    await page.goto('http://127.0.0.1:5173');
    await page.locator('.saved-workspace summary').click();
    await page.getByLabel('Saved positions', { exact: true }).selectOption(record.id);
    const builder = await page.locator('.leg-list').textContent();
    await page.getByRole('button', { name: 'Manage closes', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Manage recorded closes' });
    await dialog.getByLabel('Position action', { exact: true }).waitFor({ timeout: 5000 });
    assert.equal(await dialog.locator('form').count(), 1);
    const inventoryBox = await dialog.getByRole('heading', { name: 'Remaining inventory', exact: true }).boundingBox();
    const actionBox = await dialog.getByLabel('Position action', { exact: true }).boundingBox();
    assert.ok(inventoryBox.y < actionBox.y, 'Inventory must precede recording actions');
    await dialog.screenshot({ path: 'web/.wrangler/lifecycle-overview.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth), true);
    await dialog.screenshot({ path: 'web/.wrangler/lifecycle-overview-mobile.png' });
    await page.setViewportSize({ width: 1280, height: 720 });
    assert.equal(await dialog.getByRole('button', { name: 'Value remaining holdings' }).isDisabled(), true);
    await dialog.getByLabel('Close asset', { exact: true }).selectOption(`option:${state.legs[0].id}`);
    await dialog.getByLabel('Close quantity').fill('1');
    await dialog.getByLabel('Close price').fill('3.12345');
    await dialog.getByLabel('Close UTC datetime').fill('2026-09-04T20:00');
    await dialog.getByRole('button', { name: 'Preview close', exact: true }).click();
    await dialog.getByRole('region', { name: 'Close preview' }).waitFor();
    assert.equal(await dialog.getByLabel('Position action', { exact: true }).isDisabled(), true);
    await dialog.getByText('$3.12345 / share', { exact: false }).waitFor();
    await page.screenshot({ path: 'web/.wrangler/lifecycle-preview.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'web/.wrangler/lifecycle-preview-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1280, height: 720 });
    assert.equal(commits.length, 0);
    await dialog.getByRole('button', { name: 'Confirm recorded close' }).click();
    await dialog.getByRole('alert').waitFor();
    assert.equal(await dialog.getByLabel('Close quantity').isDisabled(), true);
    await dialog.getByRole('button', { name: 'Reload saved record' }).click();
    await dialog.getByText('The close is not confirmed in this reload.', { exact: false }).waitFor();
    assert.equal(await dialog.getByLabel('Close quantity').isDisabled(), true);
    await page.keyboard.press('Escape');
    assert.equal(await dialog.isVisible(), true);
    await dialog.getByRole('button', { name: 'Retry identical close' }).click();
    await dialog.getByRole('alert').filter({ hasText: 'Rate limited' }).waitFor();
    assert.equal(await dialog.getByLabel('Close quantity').isDisabled(), true);
    await dialog.getByRole('button', { name: 'Retry identical close' }).click();
    await dialog.getByText('No remaining assets. Position fully closed.').waitFor();
    assert.deepEqual(commits[0], commits[1]);
    assert.deepEqual(commits[0], commits[2]);
    await dialog.getByLabel('Position action', { exact: true }).selectOption('correction');
    assert.equal(await dialog.locator('form').count(), 1);
    await dialog.getByLabel('Correction original close').selectOption(commits[0].close.id);
    await dialog.getByLabel('Corrected close price').fill('3.98765');
    await dialog.getByLabel('Price correction reason').fill('Transcription correction');
    await dialog.getByRole('button', { name: 'Preview price correction' }).click();
    await dialog.getByRole('region', { name: 'Price correction preview' }).waitFor();
    assert.equal(corrections.length, 0);
    await dialog.getByRole('button', { name: 'Confirm price correction' }).click();
    await dialog.getByRole('alert').waitFor();
    assert.equal(await dialog.getByLabel('Corrected close price').isDisabled(), true);
    await dialog.getByRole('button', { name: 'Reload saved record' }).click();
    await dialog.getByText('The price correction is not confirmed in this reload.', { exact: false }).waitFor();
    await dialog.getByRole('button', { name: 'Retry identical price correction' }).click();
    await dialog.getByRole('alert').filter({ hasText: 'Correction rate limited' }).waitFor();
    assert.equal(await dialog.getByLabel('Corrected close price').isDisabled(), true);
    await dialog.getByRole('button', { name: 'Retry identical price correction' }).click();
    await dialog.getByText('Price correction recorded. The strategy builder has not changed.').waitFor();
    assert.deepEqual(corrections[0], corrections[1]);
    assert.deepEqual(corrections[0], corrections[2]);
    await dialog.getByText('Recorded closes · 1', { exact: true }).click();
    await dialog.getByText('Latest corrected price: $3.98765 / share', { exact: true }).waitFor();
    await dialog.getByText('original $3.12345 / share', { exact: false }).waitFor();
    await dialog.getByText('$163.77', { exact: true }).waitFor();
    await dialog.getByLabel('Position action', { exact: true }).selectOption('void');
    assert.equal(await dialog.locator('form').count(), 1);
    await dialog.getByLabel('Void original close').selectOption(commits[0].close.id);
    await dialog.getByLabel('Close void reason').fill('Close recorded in error');
    await dialog.getByRole('button', { name: 'Preview close void' }).click();
    const voidPreview = dialog.getByRole('region', { name: 'Close void preview' });
    await voidPreview.waitFor();
    await voidPreview.getByText(`1 contracts · long ${state.legs[0].contractId}`, { exact: true }).waitFor();
    await voidPreview.getByText('$0.00', { exact: true }).waitFor();
    assert.equal(voids.length, 0);
    await dialog.getByRole('button', { name: 'Void erroneous close', exact: true }).click();
    await dialog.getByRole('alert').waitFor();
    await dialog.getByRole('button', { name: 'Reload saved record' }).click();
    await dialog.getByText('The close void is not confirmed in this reload.', { exact: false }).waitFor();
    assert.equal(await dialog.getByLabel('Close void reason').isDisabled(), true);
    await dialog.getByRole('button', { name: 'Retry identical close void' }).click();
    await dialog.getByRole('alert').filter({ hasText: 'Void rate limited' }).waitFor();
    assert.equal(await dialog.getByLabel('Close void reason').isDisabled(), true);
    await dialog.getByRole('button', { name: 'Retry identical close void' }).click();
    await dialog.getByText('Close void recorded. The strategy builder has not changed.').waitFor();
    assert.deepEqual(voids[0], voids[1]);
    assert.deepEqual(voids[0], voids[2]);
    await dialog.getByText('VOIDED · Close recorded in error', { exact: false }).waitFor();
    await dialog.getByText('Latest corrected price: $3.98765 / share', { exact: true }).waitFor();
    assert.equal(await dialog.getByLabel('Correction original close').count(), 0);
    assert.equal(await dialog.getByLabel('Void original close').count(), 0);
    assert.equal(await dialog.locator('tbody tr').count(), 1);
    await dialog.getByText('$0.00', { exact: true }).waitFor();
    assert.equal(await page.locator('.leg-list').textContent(), builder);
    await dialog.getByRole('button', { name: 'Close close-management panel' }).click();
    assert.equal(await page.getByRole('button', { name: 'Manage closes', exact: true }).evaluate(element => document.activeElement === element), true);
    await page.getByRole('button', { name: 'Load', exact: true }).click();
    await page.getByText('Loaded saved position. Undo restores the previous position.').waitFor();
    const markedBuilder = await page.locator('.leg-list').textContent();
    await page.getByRole('button', { name: 'Manage closes', exact: true }).click();
    await dialog.getByLabel('Remaining valuation basis').selectOption('natural');
    assert.equal(valuations, 0);
    await dialog.getByRole('button', { name: 'Value remaining holdings' }).click();
    await dialog.getByRole('region', { name: 'Dated combined P/L' }).waitFor();
    await dialog.getByText('Recorded realized $70.00 + remaining unrealized $20.00 − allowance $5.00 = $85.00').waitFor();
    await dialog.getByLabel('Remaining valuation basis').selectOption('mid');
    assert.equal(await dialog.getByRole('region', { name: 'Dated combined P/L' }).count(), 0);
    assert.equal(valuations, 1);
    await dialog.getByRole('button', { name: 'Value remaining holdings' }).click();
    await dialog.getByRole('region', { name: 'Dated combined P/L' }).waitFor();
    await dialog.getByRole('button', { name: 'Reload saved record' }).click();
    assert.equal(await dialog.getByRole('region', { name: 'Dated combined P/L' }).count(), 0);
    assert.equal(await page.locator('.leg-list').textContent(), markedBuilder);
    malformedRemaining = true;
    await dialog.getByRole('button', { name: 'Value remaining holdings' }).click();
    await dialog.getByRole('region', { name: 'Dated combined P/L' }).waitFor();
    await dialog.getByRole('button', { name: 'Analyze remaining holdings', exact: true }).click();
    await dialog.getByRole('alert').waitFor();
    assert.equal(await page.locator('.leg-list').textContent(), markedBuilder);
    malformedRemaining = false;
    await dialog.getByRole('button', { name: 'Value remaining holdings' }).click();
    await dialog.getByRole('region', { name: 'Dated combined P/L' }).waitFor();
    await dialog.getByRole('button', { name: 'Analyze remaining holdings', exact: true }).click();
    await page.getByRole('heading', { name: 'Remaining holdings', exact: true }).waitFor();
    assert.equal(await page.getByLabel('Contracts', { exact: true }).inputValue(), '2');
    assert.equal(await page.getByLabel('Total cost allowance', { exact: true }).inputValue(), '0');
    assert.match(await page.locator('.saved-workspace summary').innerText(), /Unsaved position/);
    assert.deepEqual(saveMutations, []);
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    assert.equal(await page.locator('.leg-list').textContent(), markedBuilder);
    assert.deepEqual(saveMutations, []);
    assert.deepEqual(errors, []);
    console.log('Lifecycle browser PASS: closes, stable-ID retry, dated valuation, malformed import rejection, explicit detached remaining analysis and Undo.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
