const { chromium } = require('playwright');
const assert = require('node:assert/strict');
require('node:module').registerHooks({ resolve(specifier, context, next) {
  return next(specifier.startsWith('.') && !/\.[a-z]+$/i.test(specifier) ? new URL(`${specifier}.ts`, context.parentURL).href : specifier, context);
} });

(async () => {
  const { createStrategy, createMarketStrategy } = await import('../src/options.ts');
  const { calculateLotScenarioComparison } = await import('../src/lot-scenarios.ts');
  const { projectPositionLots, valuePositionLots, recordLotTransaction } = await import('../src/position-lots.ts');
  const state = createStrategy('long-put'); state.legs[0].entryPrice = 2;
  const leg = state.legs[0], at = '2026-09-05T12:00:00.000Z';
  const record = { id: 'lots-browser', title: 'Recorded roll', revision: 1, state, snapshot: null, lifecycle: null, createdAt: at, updatedAt: at };
  const lot = { id: 'initial:option:0', asset: { kind: 'option', contractId: leg.contractId, type: leg.type, strike: leg.strike, expiry: leg.expiry, multiplier: 100 }, side: 'long', quantity: 1, entryPrice: 2, at: state.valuationTimestamp, recordedAt: state.valuationTimestamp };
  const projection = { initial: state, lots: [lot], openings: [{ ...lot, originalEntryPrice: 2 }], version: 1, asOf: at, recordedAt: at, grossRealizedPnl: 0, allowance: 7, netClosedPnl: null, status: 'open' };
  const snapshot = { id: 'lots-dated-quotes', underlying: 'SPY', source: 'Tastytrade', retrievedAt: '2026-09-05T18:00:00.000Z', spotAsOf: '2026-09-05T17:59:58.000Z', spot: 100, availableExpiries: ['2026-09-18'], contracts: [{ contractId: 'SPY   260918P00100000', type: 'put', strike: 100, expiry: '2026-09-18T20:00:00.000Z', multiplier: 100, bid: 2, ask: 2.1, iv: .2, quoteAsOf: '2026-09-05T17:59:57.000Z' }] };
  snapshot.retrievedAt = '2026-09-05T18:00:00.123Z';
  const quotes = { ...record, id: 'quotes', title: 'Dated workspace quotes', state: createMarketStrategy('long-put', snapshot), snapshot };
  if (process.argv.includes('--entry-only')) {
    quotes.state.pricing.entryMode = 'fixed'; quotes.state.legs[0].contracts = 2;
    snapshot.availableExpiries.push('2026-09-25');
    snapshot.contracts.push({ ...snapshot.contracts[0], contractId: 'SPY   260925P00100000', expiry: '2026-09-25T20:00:00.000Z' });
  }
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
    const errors = [], writes = []; let previewBody, confirmed, reloads = 0;
    const entryPreviews = [];
    let valuationCalls = 0, wrongValuation = false, comparisonCalls = 0, wrongComparison = true;
    let discussionCalls = 0, discussionComparison;
    const amendmentWrites = [], openingWrites = []; let amendmentProjection, openingPreviewBody;
    page.on('pageerror', error => errors.push(error.message));
    const after = body => {
      const entryPrice = confirmed?.lifecycle.amendments?.findLast(event => event.kind === 'opening-price-correction' && event.lotId === lot.id)?.price ?? 2;
      const lots = body.transaction.opens.map(open => ({ ...open, at: body.transaction.at, recordedAt: body.transaction.recordedAt }));
      return { ...projection, lots, openings: [{ ...lot, entryPrice, originalEntryPrice: 2 }, ...lots.map(open => ({ ...open, originalEntryPrice: open.entryPrice }))], grossRealizedPnl: (body.transaction.closes[0].price - entryPrice) * 100, version: 2 };
    };
    await page.route('**/api/feed/**', route => route.fulfill({ status: 503, json: { error: { message: 'Mock feed disabled' } } }));
    await page.route('**/api/strategies**', async route => {
      const request = route.request(), path = new URL(request.url()).pathname;
      if (path === '/api/strategies') {
        assert.equal(request.method(), 'GET');
        return route.fulfill({ json: { strategies: [confirmed ?? record, quotes] } });
      }
      if (path === '/api/strategies/quotes') return route.fulfill({ json: { record: quotes } });
      if (path === '/api/strategies/quotes/lots') return route.fulfill({ json: { record: quotes, projection: projectPositionLots({ schemaVersion: 2, legacy: { schemaVersion: 1, initial: quotes.state, closes: [] }, transactions: [] }) } });
      if (path.endsWith('/lots')) {
        reloads++;
        if (confirmed && openingWrites.length === 1) return route.fulfill({ json: { record: { ...confirmed, revision: confirmed.revision + 1, lifecycle: { ...confirmed.lifecycle, amendments: [{ kind: 'opening-price-correction', ...openingWrites[0].correction, lotId: confirmed.lifecycle.transactions[0].opens[0].id }] } }, projection: after({ transaction: confirmed.lifecycle.transactions[0] }) } });
        if (confirmed && amendmentWrites.length === 1) return route.fulfill({ json: { record: { ...confirmed, revision: confirmed.revision + 1, lifecycle: { ...confirmed.lifecycle, amendments: [{ kind: 'price-correction', ...amendmentWrites[0].correction, price: 99 }] } }, projection: after(previewBody) } });
        if (confirmed) return route.fulfill({ json: { record: confirmed, projection: amendmentProjection ?? after(previewBody) } });
        // A matching transaction ID alone must not resolve an uncertain save.
        if (writes.length) {
          const wrong = structuredClone(previewBody.transaction); wrong.opens[0].entryPrice = 99;
          return route.fulfill({ json: { record: { ...record, revision: 2, lifecycle: { schemaVersion: 2, legacy: { schemaVersion: 1, initial: state, closes: [] }, transactions: [wrong] } }, projection: after(previewBody) } });
        }
        return route.fulfill({ json: { record, projection } });
      }
      const body = request.postDataJSON();
      if (process.argv.includes('--entry-only')) {
        assert.equal(path, '/api/strategies/quotes/transactions/preview');
        assert.equal(body.revision, quotes.revision);
        const lifecycle = { schemaVersion: 2, legacy: { schemaVersion: 1, initial: quotes.state, closes: [] }, transactions: [] };
        const projected = projectPositionLots(recordLotTransaction(lifecycle, body.transaction));
        entryPreviews.push({ transaction: body.transaction, projection: projected });
        return route.fulfill({ json: { revision: quotes.revision, projection: projected } });
      }
      if (path.includes('/lot-opening-price-corrections')) {
        assert.deepEqual(Object.keys(body).sort(), ['correction', 'revision']);
        assert.deepEqual(Object.keys(body.correction).sort(), ['id', 'lotId', 'price', 'reason', 'recordedAt']);
        assert.equal(body.revision, confirmed ? 2 : 1); assert.equal(body.correction.lotId, lot.id);
        assert.equal(body.correction.price, 3); assert.equal(body.correction.reason, 'Correct opening transcription');
        const projected = confirmed ? after({ transaction: confirmed.lifecycle.transactions[0] }) : { ...projection, lots: [{ ...lot, entryPrice: 3 }], openings: [{ ...lot, originalEntryPrice: 2 }] };
        projected.openings[0].entryPrice = 3;
        projected.grossRealizedPnl = confirmed ? (confirmed.lifecycle.transactions[0].closes[0].price - 3) * 100 : 0;
        if (path.endsWith('/preview')) { openingPreviewBody = body; return route.fulfill({ json: { revision: body.revision, projection: projected } }); }
        openingWrites.push(body);
        assert.deepEqual(body, openingPreviewBody);
        if (openingWrites.length === 1) return route.abort();
        if (openingWrites.length === 2) return route.fulfill({ status: 429, json: { error: { message: 'Rate limited' } } });
        confirmed = { ...confirmed, revision: confirmed.revision + 1, lifecycle: { ...confirmed.lifecycle, amendments: [{ kind: 'opening-price-correction', ...body.correction }] } };
        amendmentProjection = projected;
        return route.fulfill({ json: { record: confirmed, projection: projected } });
      }
      if (path.endsWith('/lot-discussion')) {
        discussionCalls++;
        assert.deepEqual(Object.keys(body).sort(), ['basis', 'conversation', 'request_id', 'revision', ...(body.scenario ? ['scenario'] : []), 'snapshotId', 'transaction']);
        assert.equal(body.revision, 2); assert.equal(body.snapshotId, snapshot.id); assert.equal(body.basis, 'mid');
        assert.deepEqual(body.transaction, previewBody.transaction);
        assert.equal(body.conversation.length, discussionCalls === 3 ? 3 : 1);
        const facts = { ...discussionComparison, savedId: record.id, title: record.title, transaction: structuredClone(body.transaction) };
        if (body.scenario) {
          assert.deepEqual(Object.keys(body.scenario).sort(), ['date', 'ivShift', 'spot']);
          facts.scenario = calculateLotScenarioComparison(discussionComparison, body.scenario);
          if (discussionCalls === 4) facts.scenario.scenario.spot += 1;
        }
        if (discussionCalls === 1) facts.transaction.opens[0].entryPrice += 1;
        const requestedScenarios = discussionCalls === 5 ? [calculateLotScenarioComparison(discussionComparison, { spot: 95, date: '2026-09-18T20:00:00.000Z', ivShift: .05 })] : [];
        return route.fulfill({ json: { request_id: body.request_id, facts, requestedScenarios, reply: { text: discussionCalls === 3 ? 'The entered execution remains hypothetical.' : 'The proposed total is a dated estimate, not a forecast.', assumptions: ['Same captured snapshot.'], objections: ['No verified broker fill.'], suggested_prompts: ['What changes the realized amount?'] } } });
      }
      if (path.includes('/lot-price-corrections') || path.includes('/lot-close-voids')) {
        const correction = path.includes('/lot-price-corrections'), key = correction ? 'correction' : 'void', event = body[key];
        assert.deepEqual(Object.keys(body).sort(), [key, 'revision'].sort());
        assert.equal(event.closeId, confirmed.lifecycle.transactions[0].closes[0].id);
        assert.equal(event.reason, correction ? 'Correct recorded price' : 'No actual close');
        const projected = { ...after({ transaction: confirmed.lifecycle.transactions[0] }), grossRealizedPnl: correction ? 150.12345 : 0 };
        if (!correction) projected.lots.unshift({ ...lot, entryPrice: 3 });
        if (path.endsWith('/preview')) return route.fulfill({ json: { revision: confirmed.revision, projection: projected } });
        amendmentWrites.push(body);
        if (correction && amendmentWrites.length === 1) return route.abort();
        if (correction && amendmentWrites.length === 2) return route.fulfill({ status: 429, json: { error: { message: 'Rate limited' } } });
        if (correction) assert.deepEqual(body, amendmentWrites[0]);
        confirmed = { ...confirmed, revision: confirmed.revision + 1, lifecycle: { ...confirmed.lifecycle, amendments: [...(confirmed.lifecycle.amendments ?? []), { kind: correction ? 'price-correction' : 'close-void', ...event }] } };
        amendmentProjection = projected;
        return route.fulfill({ json: { record: confirmed, projection: projected } });
      }
      if (path.endsWith('/transaction-comparison')) {
        comparisonCalls++;
        assert.deepEqual(Object.keys(body).sort(), ['basis', 'revision', 'snapshotId', 'transaction']);
        assert.equal(body.revision, 2); assert.equal(body.snapshotId, snapshot.id);
        assert.deepEqual(body.transaction, previewBody.transaction);
        const side = (entryPrice, realized) => {
          const initial = structuredClone(quotes.state); initial.feeAllowance = 7; initial.pricing.entryMode = 'fixed';
          const remainingState = structuredClone(initial); remainingState.feeAllowance = 0; remainingState.legs[0].entryPrice = entryPrice;
          const held = { ...lot, asset: { ...lot.asset, ...snapshot.contracts[0], kind: 'option' }, entryPrice };
          return { projection: { ...projection, initial, lots: [held], grossRealizedPnl: realized }, valuation: { snapshotId: snapshot.id, basis: body.basis, combinedPnl: realized + (2.05 - entryPrice) * 100 - 7, grossRealizedPnl: realized, unrealizedPnl: (2.05 - entryPrice) * 100, allowance: 7, retrievedAt: snapshot.retrievedAt, oldestQuoteAt: snapshot.contracts[0].quoteAsOf, newestQuoteAt: snapshot.spotAsOf, historical: true, remainingState, lotMarks: [{ lotId: held.id, quantity: 1, entryPrice, mark: 2.05, unrealizedPnl: (2.05 - entryPrice) * 100 }] } };
        };
        discussionComparison = { revision: 2, transactionId: wrongComparison ? 'different-transaction' : body.transaction.id, snapshotId: snapshot.id, basis: body.basis, before: side(2, 0), after: side(5, 100) };
        return route.fulfill({ json: discussionComparison });
      }
      if (path.endsWith('/valuation')) {
        valuationCalls++;
        assert.deepEqual(Object.keys(body).sort(), ['basis', 'revision', 'snapshotId']);
        assert.equal(body.snapshotId, snapshot.id); assert.equal(body.revision, 2);
        return route.fulfill({ json: { revision: 2, valuation: { snapshotId: wrongValuation ? 'wrong-quotes' : snapshot.id, basis: body.basis, retrievedAt: snapshot.retrievedAt, oldestQuoteAt: snapshot.contracts[0].quoteAsOf, newestQuoteAt: snapshot.spotAsOf, historical: true, grossRealizedPnl: 70, unrealizedPnl: 20, allowance: 5, combinedPnl: 85, remainingState: null, analysisUnavailable: 'Mock chart unavailable', lotMarks: [{ lotId: confirmed.lifecycle.transactions[0].opens[0].id, quantity: 1, entryPrice: 4.98765, mark: 5.18765, unrealizedPnl: 20 }], disclosure: 'Dated estimate, not a fill or live return.' } } });
      }
      assert.deepEqual(Object.keys(body).sort(), ['revision', 'transaction']);
      assert.equal(body.revision, confirmed ? 2 : 1); assert.equal(body.transaction.at, at);
      assert.equal(body.transaction.closes[0].lotId, confirmed ? confirmed.lifecycle.transactions[0].opens[0].id : lot.id);
      assert.equal(body.transaction.closes[0].price, 3.12345);
      assert.equal(body.transaction.opens[0].entryPrice, 4.98765);
      assert.match(body.transaction.id, /^[0-9a-f-]{36}$/);
      assert.match(body.transaction.closes[0].id, /^[0-9a-f-]{36}$/);
      assert.match(body.transaction.opens[0].id, /^[0-9a-f-]{36}$/);
      if (path.endsWith('/transactions/preview')) { previewBody = body; return route.fulfill({ json: { revision: body.revision, projection: after(body) } }); }
      assert.ok(path.endsWith('/transactions'));
      writes.push(body);
      if (writes.length === 1) return route.abort();
      if (writes.length === 2) return route.fulfill({ status: 429, json: { error: { message: 'Rate limited' } } });
      confirmed = { ...record, revision: 2, lifecycle: { schemaVersion: 2, legacy: { schemaVersion: 1, initial: state, closes: [] }, transactions: [body.transaction] } };
      return route.fulfill({ json: { record: confirmed, projection: after(body) } });
    });
    await page.goto('http://127.0.0.1:5173');
    assert.equal(await page.getByRole('button', { name: 'Compare adjustment', exact: true }).isDisabled(), true);
    await page.locator('.saved-workspace > summary').click();
    if (process.argv.includes('--entry-only')) {
      await page.getByLabel('Saved positions', { exact: true }).selectOption(quotes.id);
      await page.getByRole('button', { name: 'Load', exact: true }).click();
      await page.getByText('Loaded saved position. Undo restores the previous position.').waitFor();
      const held = await page.locator('.leg-list').textContent();
      await page.getByLabel('Saved positions', { exact: true }).selectOption(record.id);
      await page.locator('.saved-workspace > summary').click();
      const adjustment = page.getByRole('group', { name: 'Saved position adjustment', exact: true });
      assert.match(await adjustment.innerText(), /Dated workspace quotes/);
      await adjustment.getByRole('button', { name: 'Compare adjustment', exact: true }).click();
      const panel = page.getByRole('dialog', { name: 'Manage lots and rolls' });
      await panel.getByRole('heading', { name: quotes.title, exact: true }).waitFor();
      await panel.getByLabel('Close lot initial:option:0', { exact: true }).check();
      await panel.getByLabel('Close quantity initial:option:0', { exact: true }).fill('1');
      await panel.getByLabel('Close price initial:option:0', { exact: true }).fill('3');
      await panel.getByLabel('Transaction UTC datetime').fill('2026-09-06T12:00');
      await panel.getByRole('button', { name: 'Preview transaction', exact: true }).click();
      await panel.getByRole('button', { name: 'Confirm recorded transaction', exact: true }).waitFor();
      assert.equal(entryPreviews[0].projection.lots[0].quantity, 1);
      assert.equal(entryPreviews[0].transaction.opens.length, 0);
      assert.equal(entryPreviews[0].projection.grossRealizedPnl, 95);
      assert.equal(quotes.lifecycle, null);
      assert.deepEqual(writes, []);
      await panel.screenshot({ path: '.wrangler/adjustment-entry-desktop.png' });
      await page.setViewportSize({ width: 390, height: 844 });
      assert.equal(await panel.evaluate(el => el.scrollWidth <= el.clientWidth), true);
      await panel.getByRole('button', { name: 'Close lot-management panel' }).click();
      assert.equal(await page.locator('.leg-list').textContent(), held);
      assert.equal(await adjustment.isVisible(), true);
      await adjustment.screenshot({ path: '.wrangler/adjustment-entry-mobile.png' });
      await page.getByLabel('Expiry', { exact: true }).selectOption('2026-09-25T20:00:00.000Z');
      const proposed = await page.locator('.leg-list').textContent();
      await adjustment.getByRole('button', { name: 'Compare adjustment', exact: true }).click();
      await panel.getByRole('heading', { name: quotes.title, exact: true }).waitFor();
      await panel.getByLabel('Close lot initial:option:0', { exact: true }).check();
      await panel.getByLabel('Close price initial:option:0', { exact: true }).fill('3');
      const opening = panel.locator('input[aria-label^="Open leg "]').first();
      const openingId = (await opening.getAttribute('aria-label')).slice('Open leg '.length);
      await opening.check();
      await panel.getByLabel(`Open price ${openingId}`, { exact: true }).fill('4');
      await panel.getByLabel('Transaction UTC datetime').fill('2026-09-06T12:00');
      await panel.getByRole('button', { name: 'Preview transaction', exact: true }).click();
      await panel.getByRole('button', { name: 'Confirm recorded transaction', exact: true }).waitFor();
      assert.equal(entryPreviews.length, 2);
      assert.equal(entryPreviews[1].transaction.closes[0].quantity, 2);
      assert.equal(entryPreviews[1].projection.lots.length, 1);
      assert.equal(entryPreviews[1].projection.lots[0].asset.expiry, '2026-09-25T20:00:00.000Z');
      assert.equal(entryPreviews[1].projection.grossRealizedPnl, 190);
      assert.equal(quotes.state.legs[0].expiry, '2026-09-18T20:00:00.000Z');
      assert.equal(quotes.lifecycle, null);
      await panel.getByRole('button', { name: 'Close lot-management panel' }).click();
      assert.equal(await page.locator('.leg-list').textContent(), proposed);
      assert.deepEqual(writes, []); assert.deepEqual(errors, []);
      console.log('Adjustment entry PASS: loaded identity, collapsed library, narrow layout, authoritative partial-close and changed-expiry roll previews, no writes.');
      return;
    }
    await page.getByLabel('Saved positions', { exact: true }).selectOption(record.id);
    const builder = await page.locator('.leg-list').textContent();
    await page.getByRole('button', { name: 'Manage lots & rolls', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Manage lots and rolls' });
    await dialog.getByRole('button', { name: 'Value remaining lots', exact: true }).waitFor();
    assert.equal(await dialog.getByRole('button', { name: 'Value remaining lots', exact: true }).isDisabled(), true);
    assert.equal(valuationCalls, 0);
    await dialog.getByLabel('Lot action', { exact: true }).selectOption('opening-correction');
    await dialog.getByLabel('Recorded opening lot', { exact: true }).selectOption(lot.id);
    await dialog.getByLabel('Corrected lot opening price', { exact: true }).fill('3');
    await dialog.getByLabel('Lot amendment reason', { exact: true }).fill('Correct opening transcription');
    await dialog.getByRole('button', { name: 'Preview lot amendment', exact: true }).click();
    await dialog.getByRole('region', { name: 'Lot amendment preview', exact: true }).waitFor();
    assert.equal(openingWrites.length, 0); assert.equal(record.lifecycle, null);
    assert.equal(await page.locator('.leg-list').textContent(), builder);
    await dialog.getByRole('button', { name: 'Edit amendment', exact: true }).click();
    await dialog.getByLabel('Lot action', { exact: true }).selectOption('transaction');
    await dialog.getByLabel(`Close lot ${lot.id}`, { exact: true }).check();
    assert.equal(await dialog.getByLabel(`Close price ${lot.id}`, { exact: true }).inputValue(), '');
    await dialog.getByLabel(`Close price ${lot.id}`, { exact: true }).fill('3.12345');
    const opening = dialog.locator('input[aria-label^="Open leg "]').first();
    const openId = (await opening.getAttribute('aria-label')).slice('Open leg '.length);
    await opening.check();
    assert.equal(await dialog.getByLabel(`Open price ${openId}`, { exact: true }).inputValue(), '');
    await dialog.getByLabel(`Open price ${openId}`, { exact: true }).fill('4.98765');
    await dialog.getByLabel('Transaction UTC datetime').fill('2026-09-05T12:00');
    await dialog.getByRole('button', { name: 'Preview transaction', exact: true }).click();
    const confirm = dialog.getByRole('button', { name: 'Confirm recorded transaction', exact: true });
    await confirm.waitFor(); assert.equal(writes.length, 0);
    const transactionPreview = dialog.getByRole('region', { name: 'Transaction preview', exact: true });
    assert.match(await transactionPreview.innerText(), /projected recorded totals after confirmation/);
    assert.doesNotMatch(await transactionPreview.innerText(), /This is recorded execution accounting/);
    await dialog.getByRole('button', { name: 'Edit transaction', exact: true }).click();
    assert.equal(await transactionPreview.count(), 0);
    assert.equal(writes.length, 0); assert.equal(confirmed, undefined);
    await dialog.getByRole('button', { name: 'Preview transaction', exact: true }).click();
    await confirm.waitFor();
    assert.match(await dialog.innerText(), /3\.12345/); assert.match(await dialog.innerText(), /4\.98765/);
    await dialog.screenshot({ path: 'web/.wrangler/lots-preview.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await dialog.screenshot({ path: 'web/.wrangler/lots-preview-mobile.png' });
    await page.setViewportSize({ width: 1280, height: 800 });
    await confirm.click();
    const retry = dialog.getByRole('button', { name: /Retry identical/ });
    await retry.waitFor();
    assert.match(await transactionPreview.innerText(), /may already be saved/);
    assert.equal(await dialog.getByRole('button', { name: 'Edit transaction', exact: true }).isDisabled(), true);
    assert.equal(await dialog.getByRole('button', { name: 'Close lot-management panel' }).isDisabled(), true);
    await page.keyboard.press('Escape'); assert.equal(await dialog.isVisible(), true);
    await dialog.getByRole('button', { name: 'Reload saved record', exact: true }).click();
    await retry.waitFor(); assert.ok(reloads >= 2);
    await retry.click(); await dialog.getByRole('alert').filter({ hasText: 'Rate limited' }).waitFor();
    assert.equal(await dialog.getByRole('button', { name: 'Edit transaction', exact: true }).isDisabled(), true);
    await retry.click();
    await dialog.getByRole('button', { name: 'Preview transaction', exact: true }).waitFor();
    assert.equal(writes.length, 3); for (const body of writes) assert.deepEqual(body, previewBody);
    assert.equal(await page.locator('.leg-list').textContent(), builder);
    await dialog.getByRole('button', { name: 'Close lot-management panel' }).click();
    assert.equal(await dialog.count(), 0);
    await page.getByLabel('Saved positions', { exact: true }).selectOption(quotes.id);
    await page.getByRole('button', { name: 'Load', exact: true }).click();
    await page.getByText('Loaded saved position. Undo restores the previous position.').waitFor();
    await page.getByLabel('Saved positions', { exact: true }).selectOption(record.id);
    await page.getByRole('button', { name: 'Manage lots & rolls', exact: true }).click();
    const value = dialog.getByRole('button', { name: 'Value remaining lots', exact: true });
    await value.waitFor(); assert.equal(valuationCalls, 0);
    await dialog.getByLabel('Lot valuation basis').selectOption('natural');
    await value.click();
    const combined = dialog.getByRole('region', { name: 'Dated lot combined P/L' });
    await combined.waitFor();
    assert.match(await combined.innerText(), /85\.00/);
    assert.match(await combined.innerText(), /70\.00/);
    assert.match(await combined.innerText(), /20\.00/);
    assert.match(await combined.innerText(), /5\.00/);
    assert.match(await combined.innerText(), /Historical/);
    assert.match(await combined.innerText(), /Natural/);
    await dialog.screenshot({ path: 'web/.wrangler/lots-valuation.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    await combined.scrollIntoViewIfNeeded();
    assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await dialog.screenshot({ path: 'web/.wrangler/lots-valuation-mobile.png' });
    await page.setViewportSize({ width: 1280, height: 800 });
    await dialog.getByLabel('Lot valuation basis').selectOption('mid');
    assert.equal(await combined.count(), 0);
    wrongValuation = true; await value.click();
    await dialog.getByRole('alert').waitFor(); assert.equal(await combined.count(), 0);
    wrongValuation = false; await value.click(); await combined.waitFor();
    await dialog.getByRole('button', { name: 'Reload saved record', exact: true }).click();
    assert.equal(await combined.count(), 0); assert.equal(valuationCalls, 3);
    assert.equal(writes.length, 3);
    const heldId = confirmed.lifecycle.transactions[0].opens[0].id;
    await dialog.getByLabel(`Close lot ${heldId}`, { exact: true }).check();
    await dialog.getByLabel(`Close price ${heldId}`, { exact: true }).fill('3.12345');
    const nextOpening = dialog.locator('input[aria-label^="Open leg "]').first();
    const nextId = (await nextOpening.getAttribute('aria-label')).slice('Open leg '.length);
    await nextOpening.check();
    await dialog.getByLabel(`Open price ${nextId}`, { exact: true }).fill('4.98765');
    await dialog.getByLabel('Transaction UTC datetime').fill('2026-09-05T12:00');
    await dialog.getByRole('button', { name: 'Preview transaction', exact: true }).click();
    await dialog.getByRole('button', { name: 'Compare dated P/L', exact: true }).click();
    const comparison = dialog.getByRole('region', { name: 'Before and after dated P/L' });
    await dialog.getByRole('alert').waitFor(); assert.equal(await comparison.count(), 0);
    wrongComparison = false;
    await dialog.getByRole('button', { name: 'Compare dated P/L', exact: true }).click();
    await comparison.waitFor();
    assert.match(await comparison.innerText(), /2\.00/); assert.match(await comparison.innerText(), /202\.00/);
    assert.equal(comparisonCalls, 2); assert.equal(writes.length, 3);
    const discussion = dialog.getByRole('region', { name: 'Read-only lot discussion', exact: true });
    await discussion.getByLabel('Comparison question', { exact: true }).fill('Why consider this roll?');
    await discussion.getByRole('button', { name: 'Discuss this comparison', exact: true }).click();
    await discussion.getByRole('alert').waitFor();
    assert.equal(await discussion.getByText('The proposed total is a dated estimate, not a forecast.', { exact: true }).count(), 0);
    assert.equal(await discussion.getByLabel('Comparison question', { exact: true }).inputValue(), 'Why consider this roll?');
    await discussion.getByRole('button', { name: 'Discuss this comparison', exact: true }).click();
    await discussion.getByText('The proposed total is a dated estimate, not a forecast.', { exact: true }).waitFor();
    await discussion.getByRole('button', { name: 'What changes the realized amount?', exact: true }).click();
    await discussion.getByRole('button', { name: 'Discuss this comparison', exact: true }).click();
    await discussion.getByText('The entered execution remains hypothetical.', { exact: true }).waitFor();
    assert.equal(discussionCalls, 3); assert.equal(writes.length, 3);
    await discussion.scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-discussion.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await discussion.scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-discussion-mobile.png' });
    await page.setViewportSize({ width: 1280, height: 800 });
    await discussion.getByLabel('Comparison question', { exact: true }).fill('x'.repeat(12001));
    await discussion.getByRole('button', { name: 'Discuss this comparison', exact: true }).click();
    await discussion.getByRole('alert').waitFor();
    assert.equal(discussionCalls, 3);
    assert.equal((await discussion.getByLabel('Comparison question', { exact: true }).inputValue()).length, 12001);
    await discussion.getByLabel('Comparison question', { exact: true }).fill('');
    await comparison.scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-comparison.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await comparison.scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-comparison-mobile.png' });
    await page.setViewportSize({ width: 1280, height: 800 });
    assert.equal(await dialog.getByLabel('Comparison scenario UTC datetime', { exact: true }).inputValue(), '2026-09-05T18:00:01');
    await dialog.getByLabel('Comparison scenario spot', { exact: true }).fill('100');
    await dialog.getByLabel('Comparison scenario UTC datetime', { exact: true }).fill('2026-09-18T20:00');
    await dialog.getByRole('button', { name: 'Model both positions', exact: true }).click();
    const scenario = dialog.getByRole('region', { name: 'Modeled roll comparison' });
    await scenario.waitFor();
    assert.match(await scenario.innerText(), /207\.00/); assert.match(await scenario.innerText(), /407\.00/);
    assert.equal(await scenario.getByRole('img', { name: 'Held and proposed modeled P/L curves' }).count(), 1);
    assert.equal(await discussion.getByText('The entered execution remains hypothetical.', { exact: true }).count(), 0);
    await discussion.getByLabel('Comparison question', { exact: true }).fill('Compare this expiry scenario.');
    await discussion.getByRole('button', { name: 'Discuss this comparison', exact: true }).click();
    await discussion.getByRole('alert').waitFor();
    assert.match(await discussion.getByRole('alert').innerText(), /scenario changed/);
    await discussion.getByRole('button', { name: 'Discuss this comparison', exact: true }).click();
    await discussion.getByText(/Server model european-bsm-v1/).waitFor();
    assert.ok(await discussion.getByText('AI interpretation, assumptions and objections may contain errors. Calculated results are shown separately.', { exact: true }).count() > 0);
    assert.match(await discussion.innerText(), /held -\$207\.00 · proposed -\$407\.00/);
    assert.equal(discussionCalls, 5); assert.equal(writes.length, 3);
    const requested = discussion.getByRole('region', { name: 'Conversation scenario calculations', exact: true });
    await requested.waitFor();
    assert.match(await requested.innerText(), /spot \$95\.00/);
    assert.match(await requested.innerText(), /Held \$293\.00 · proposed \$93\.00/);
    assert.equal(await dialog.getByLabel('Comparison scenario spot', { exact: true }).inputValue(), '100');
    await requested.getByRole('button', { name: 'Show scenario on chart', exact: true }).click();
    await scenario.getByText('Held at $95.00', { exact: true }).waitFor();
    assert.match(await scenario.innerText(), /293\.00/); assert.match(await scenario.innerText(), /93\.00/);
    const inspect = scenario.getByRole('slider', { name: 'Inspect comparison price', exact: true });
    const inspection = scenario.getByRole('status', { name: 'Comparison price inspection', exact: true });
    await inspect.focus(); await inspect.press('Home');
    assert.match(await inspection.innerText(), /72\.20/); assert.match(await inspection.innerText(), /2,573\.00/); assert.match(await inspection.innerText(), /2,373\.00/);
    await inspect.press('End');
    assert.match(await inspection.innerText(), /117\.80/); assert.match(await inspection.innerText(), /-\$207\.00/); assert.match(await inspection.innerText(), /-\$407\.00/);
    const curve = scenario.getByRole('img', { name: 'Held and proposed modeled P/L curves', exact: true });
    const bounds = await curve.boundingBox();
    await page.mouse.move(bounds.x + bounds.width * (74 + 510 / 2) / 620, bounds.y + bounds.height / 2);
    assert.match(await inspection.innerText(), /95\.00/); assert.match(await inspection.innerText(), /\$293\.00/);
    assert.equal(await dialog.getByLabel('Comparison scenario spot', { exact: true }).inputValue(), '100');
    assert.equal(await requested.count(), 1); assert.equal(discussionCalls, 5); assert.equal(writes.length, 3);
    await scenario.getByRole('button', { name: 'Return to selected scenario', exact: true }).click();
    await scenario.getByText('Held at $100.00', { exact: true }).waitFor();
    assert.match(await inspection.innerText(), /100\.00/);
    await inspect.focus(); await inspect.press('Home');
    assert.match(await inspection.innerText(), /76\.00/);
    await requested.getByRole('button', { name: 'Show scenario on chart', exact: true }).click();
    await scenario.getByText('Held at $95.00', { exact: true }).waitFor();
    await scenario.getByRole('button', { name: 'Return to selected scenario', exact: true }).click();
    assert.match(await inspection.innerText(), /100\.00/);
    await requested.getByRole('button', { name: 'Show scenario on chart', exact: true }).click();
    await scenario.getByText('Held at $95.00', { exact: true }).waitFor();
    await scenario.scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-scenario.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    await scenario.scrollIntoViewIfNeeded();
    assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await dialog.screenshot({ path: 'web/.wrangler/lots-scenario-mobile.png' });
    await inspection.scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-inspection-mobile.png' });
    await requested.scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-conversation-scenario-mobile.png' });
    await page.setViewportSize({ width: 1280, height: 800 });
    await dialog.getByLabel('Comparison scenario spot', { exact: true }).fill('99');
    assert.equal(await scenario.count(), 0);
    assert.equal(await discussion.getByText(/Server model european-bsm-v1/).count(), 0);
    assert.equal(await requested.count(), 0);
    await dialog.getByRole('button', { name: 'Edit transaction', exact: true }).click();
    assert.equal(await comparison.count(), 0);
    assert.equal(await discussion.count(), 0);
    const unchangedBuilder = await page.locator('.leg-list').textContent();
    await dialog.getByLabel('Lot action', { exact: true }).selectOption('opening-correction');
    const recordedOpening = dialog.getByLabel('Recorded opening lot', { exact: true });
    assert.match(await recordedOpening.locator(`option[value="${lot.id}"]`).innerText(), /fully closed/);
    await recordedOpening.selectOption(lot.id);
    await dialog.getByLabel('Corrected lot opening price', { exact: true }).fill('3');
    await dialog.getByLabel('Lot amendment reason', { exact: true }).fill('Correct opening transcription');
    await dialog.getByRole('button', { name: 'Preview lot amendment', exact: true }).click();
    const openingPreview = dialog.getByRole('region', { name: 'Lot amendment preview', exact: true });
    await openingPreview.waitFor();
    assert.match(await openingPreview.innerText(), /Opening basis per share/);
    assert.match(await openingPreview.innerText(), /-\$100\.00/);
    assert.match(await openingPreview.innerText(), /12\.35/);
    assert.equal(openingWrites.length, 0);
    assert.equal(confirmed.lifecycle.legacy.initial.legs[0].entryPrice, 2);
    assert.equal(await page.locator('.leg-list').textContent(), unchangedBuilder);
    await openingPreview.getByRole('button', { name: 'Confirm price correction', exact: true }).click();
    const retryOpening = dialog.getByRole('button', { name: 'Retry identical amendment', exact: true });
    await retryOpening.waitFor();
    assert.equal(await dialog.getByRole('button', { name: 'Edit amendment', exact: true }).isDisabled(), true);
    await dialog.getByRole('button', { name: 'Reload saved record', exact: true }).click();
    await retryOpening.waitFor();
    assert.equal(await dialog.getByRole('button', { name: 'Edit amendment', exact: true }).isDisabled(), true);
    assert.match(await openingPreview.innerText(), /may already be saved/);
    await retryOpening.click(); await dialog.getByRole('alert').filter({ hasText: 'Rate limited' }).waitFor();
    assert.equal(await dialog.getByLabel('Lot action', { exact: true }).isDisabled(), true);
    await retryOpening.click(); await retryOpening.waitFor({ state: 'detached' });
    assert.equal(openingWrites.length, 3);
    for (const body of openingWrites) assert.deepEqual(body, openingPreviewBody);
    assert.equal(confirmed.lifecycle.legacy.initial.legs[0].entryPrice, 2);
    assert.equal(confirmed.lifecycle.transactions[0].opens[0].entryPrice, 4.98765);
    assert.equal(await page.locator('.leg-list').textContent(), unchangedBuilder);
    await dialog.getByLabel('Lot action', { exact: true }).selectOption('correction');
    const closeId = confirmed.lifecycle.transactions[0].closes[0].id;
    await dialog.getByLabel('Recorded lot close', { exact: true }).selectOption(closeId);
    await dialog.getByLabel('Corrected lot close price', { exact: true }).fill('4.5012345');
    await dialog.getByLabel('Lot amendment reason', { exact: true }).fill('Correct recorded price');
    await dialog.getByRole('button', { name: 'Preview lot amendment', exact: true }).click();
    await dialog.getByRole('button', { name: 'Confirm price correction', exact: true }).waitFor();
    assert.equal(amendmentWrites.length, 0);
    const amendmentPreview = dialog.getByRole('region', { name: 'Lot amendment preview', exact: true });
    assert.match(await amendmentPreview.innerText(), /projected recorded totals after confirmation/);
    assert.match(await dialog.innerText(), /4\.5012345/);
    await dialog.getByRole('region', { name: 'Lot amendment preview' }).scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-amendment.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await dialog.getByRole('region', { name: 'Lot amendment preview' }).scrollIntoViewIfNeeded();
    await dialog.screenshot({ path: 'web/.wrangler/lots-amendment-mobile.png' });
    await page.setViewportSize({ width: 1280, height: 800 });
    await dialog.getByRole('button', { name: 'Confirm price correction', exact: true }).click();
    const retryAmendment = dialog.getByRole('button', { name: 'Retry identical amendment', exact: true });
    await retryAmendment.waitFor();
    assert.match(await amendmentPreview.innerText(), /may already be saved/);
    assert.equal(await dialog.getByRole('button', { name: 'Close lot-management panel' }).isDisabled(), true);
    await page.keyboard.press('Escape'); assert.equal(await dialog.isVisible(), true);
    await dialog.getByRole('button', { name: 'Reload saved record', exact: true }).click();
    assert.equal(await dialog.getByRole('button', { name: 'Edit amendment', exact: true }).isDisabled(), true);
    await retryAmendment.click(); await dialog.getByRole('alert').waitFor();
    assert.equal(await dialog.getByLabel('Lot action', { exact: true }).isDisabled(), true);
    await retryAmendment.click(); await retryAmendment.waitFor({ state: 'detached' });
    assert.equal(amendmentWrites.length, 3);
    await dialog.getByLabel('Lot action', { exact: true }).selectOption('void');
    await dialog.getByLabel('Recorded lot close', { exact: true }).selectOption(closeId);
    await dialog.getByLabel('Lot amendment reason', { exact: true }).fill('No actual close');
    await dialog.getByRole('button', { name: 'Preview lot amendment', exact: true }).click();
    await dialog.getByRole('button', { name: 'Void erroneous lot close', exact: true }).waitFor();
    assert.equal(amendmentWrites.length, 3);
    await dialog.getByRole('button', { name: 'Void erroneous lot close', exact: true }).click();
    await dialog.getByRole('button', { name: 'Void erroneous lot close', exact: true }).waitFor({ state: 'detached' });
    assert.equal(amendmentWrites.length, 4);
    await dialog.getByText('Recorded lot activity', { exact: true }).click();
    assert.match(await dialog.innerText(), /No actual close/);
    assert.match(await dialog.innerText(), /Voided/);
    assert.match(await dialog.innerText(), /Correct opening transcription/);
    assert.equal(confirmed.lifecycle.amendments[0].kind, 'opening-price-correction');
    assert.equal(await page.locator('.leg-list').textContent(), unchangedBuilder);
    await dialog.getByRole('button', { name: 'Close lot-management panel' }).click();
    assert.deepEqual(errors, []);

    const analysisPage = await browser.newPage({ viewport: { width: 1280, height: 800 } });
    analysisPage.on('pageerror', error => errors.push(error.message));
    const openingSnapshot = { ...snapshot, retrievedAt: '2026-09-05T17:00:00.000Z', spotAsOf: '2026-09-05T16:59:58.000Z', contracts: snapshot.contracts.map(contract => ({ ...contract, quoteAsOf: '2026-09-05T16:59:57.000Z' })) };
    const initial = createMarketStrategy('long-put', openingSnapshot);
    initial.legs[0].entryPrice = 2; initial.legs[0].contracts = 2;
    initial.pricing.entryMode = 'fixed'; initial.stock = { shares: -10, entryPrice: 95 }; initial.feeAllowance = 7;
    const openingAsset = { kind: 'option', contractId: initial.legs[0].contractId, type: initial.legs[0].type, strike: initial.legs[0].strike, expiry: initial.legs[0].expiry, multiplier: 100 };
    const lifecycle = { schemaVersion: 2, legacy: { schemaVersion: 1, initial, closes: [] }, transactions: [{ id: 'analysis-add', at: '2026-09-05T17:10:00.000Z', recordedAt: '2026-09-05T17:10:00.000Z', closes: [{ id: 'analysis-close', lotId: 'initial:option:0', quantity: 1, price: 2.5 }], opens: [{ id: 'analysis-option', asset: openingAsset, side: 'long', quantity: 1, entryPrice: 5 }, { id: 'analysis-stock', asset: { kind: 'stock', symbol: initial.underlying }, side: 'short', quantity: 10, entryPrice: 105 }] }], amendments: [{ kind: 'opening-price-correction', id: 'analysis-option-basis', lotId: 'initial:option:0', price: 3, reason: 'Correct option basis', recordedAt: '2026-09-05T17:11:00.000Z' }, { kind: 'opening-price-correction', id: 'analysis-stock-basis', lotId: 'initial:stock', price: 97, reason: 'Correct stock basis', recordedAt: '2026-09-05T17:12:00.000Z' }] };
    const analysisRecord = { ...record, id: 'corrected-analysis', title: 'Corrected lot basis', state: initial, snapshot: openingSnapshot, lifecycle, revision: 4 };
    const analysisProjection = projectPositionLots(lifecycle);
    const correctValuation = valuePositionLots(lifecycle, snapshot, 'mid');
    assert.equal(correctValuation.remainingState.legs[0].entryPrice, 4);
    assert.equal(correctValuation.remainingState.legs[0].contracts, 2);
    assert.deepEqual(correctValuation.remainingState.stock, { shares: -20, entryPrice: 101 });
    assert.equal(correctValuation.remainingState.feeAllowance, 0);
    let invalidAnalysis = '', analysisReads = 0;
    const analysisWrites = [];
    await analysisPage.route('**/api/feed/**', route => route.fulfill({ status: 503, json: { error: { message: 'Mock feed disabled' } } }));
    await analysisPage.route('**/api/strategies**', async route => {
      const request = route.request(), path = new URL(request.url()).pathname;
      if (request.method() === 'GET') {
        if (path === '/api/strategies') return route.fulfill({ json: { strategies: [quotes, analysisRecord] } });
        if (path.endsWith('/quotes')) return route.fulfill({ json: { record: quotes } });
        assert.equal(path, `/api/strategies/${analysisRecord.id}/lots`);
        return route.fulfill({ json: { record: analysisRecord, projection: analysisProjection } });
      }
      if (path.endsWith('/valuation')) {
        analysisReads++;
        assert.deepEqual(request.postDataJSON(), { revision: 4, snapshotId: snapshot.id, basis: 'mid' });
        const valuation = structuredClone(correctValuation);
        if (invalidAnalysis === 'cost') valuation.remainingState.legs[0].entryPrice = 3.5;
        if (invalidAnalysis === 'quantity') valuation.remainingState.legs[0].contracts = 1;
        if (invalidAnalysis === 'stock') valuation.remainingState.stock.shares = 20;
        if (invalidAnalysis === 'unavailable') { valuation.remainingState = null; valuation.analysisUnavailable = 'Mock chart unavailable'; }
        return route.fulfill({ json: { revision: 4, valuation } });
      }
      analysisWrites.push(path);
      return route.fulfill({ status: 500, json: { error: { message: 'Unexpected saved-position write' } } });
    });
    await analysisPage.goto('http://127.0.0.1:5173');
    await analysisPage.locator('.saved-workspace > summary').click();
    await analysisPage.getByLabel('Saved positions', { exact: true }).selectOption(quotes.id);
    await analysisPage.getByRole('button', { name: 'Load', exact: true }).click();
    await analysisPage.getByText('Loaded saved position. Undo restores the previous position.').waitFor();
    const beforeAnalysis = await analysisPage.locator('.leg-list').textContent();
    const beforePremium = await analysisPage.getByLabel('Entry premium', { exact: true }).inputValue();
    const beforeAllowance = await analysisPage.getByLabel('Total cost allowance', { exact: true }).inputValue();
    await analysisPage.getByLabel('Saved positions', { exact: true }).selectOption(analysisRecord.id);
    await analysisPage.getByRole('button', { name: 'Manage lots & rolls', exact: true }).click();
    const analysisDialog = analysisPage.getByRole('dialog', { name: 'Manage lots and rolls' });
    const valueHoldings = analysisDialog.getByRole('button', { name: 'Value remaining lots', exact: true });
    const analyze = analysisDialog.getByRole('button', { name: 'Analyze remaining holdings', exact: true });
    await valueHoldings.click();
    await analyze.waitFor({ timeout: 5000 });
    for (const malformed of ['cost', 'quantity', 'stock']) {
      invalidAnalysis = malformed;
      await valueHoldings.click(); await analyze.click();
      await analysisDialog.getByRole('alert').waitFor();
      assert.equal(await analysisPage.locator('.leg-list').textContent(), beforeAnalysis);
      assert.equal(await analysisPage.getByLabel('Entry premium', { exact: true }).inputValue(), beforePremium);
      assert.deepEqual(analysisWrites, []);
    }
    invalidAnalysis = 'unavailable';
    await valueHoldings.click();
    await analysisDialog.getByText('Mock chart unavailable', { exact: false }).waitFor();
    assert.equal(await analyze.count(), 0);
    invalidAnalysis = '';
    await valueHoldings.click(); await analyze.click();
    await analysisPage.getByText('Separate unsaved analysis of remaining holdings. Excludes recorded realized P/L and the original position allowance. Saved history is unchanged; Undo restores the previous strategy.', { exact: true }).waitFor();
    assert.equal(await analysisPage.getByLabel('Entry premium', { exact: true }).inputValue(), '4');
    assert.equal(await analysisPage.getByLabel('Contracts', { exact: true }).inputValue(), '2');
    assert.equal(await analysisPage.getByLabel('Shares', { exact: true }).inputValue(), '-20');
    assert.equal(await analysisPage.getByLabel('Share entry cost', { exact: true }).inputValue(), '101');
    assert.equal(await analysisPage.getByLabel('Total cost allowance', { exact: true }).inputValue(), '0');
    assert.equal(await analysisPage.getByLabel('Saved positions', { exact: true }).inputValue(), '');
    assert.equal(await analysisPage.getByLabel('Saved strategy title', { exact: true }).inputValue(), '');
    assert.deepEqual(analysisWrites, []); assert.equal(analysisReads, 6);
    assert.equal(await analysisDialog.isVisible(), false);
    await analysisPage.getByRole('button', { name: 'Undo', exact: true }).click();
    assert.equal(await analysisPage.locator('.leg-list').textContent(), beforeAnalysis);
    assert.equal(await analysisPage.getByLabel('Entry premium', { exact: true }).inputValue(), beforePremium);
    assert.equal(await analysisPage.getByLabel('Total cost allowance', { exact: true }).inputValue(), beforeAllowance);
    assert.equal(await analysisPage.getByLabel('Shares', { exact: true }).count(), 0);
    assert.deepEqual(analysisWrites, []); assert.deepEqual(errors, []);
    console.log('Lots browser PASS: atomic/opening-correction retries, closed-lot basis preview, dated/scenario comparisons, corrected remaining-holdings import, mismatch rejection and Undo.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
